# Nom de notre workflow
name: "Snort Demo"

# Événements sur lesquels il doit être déclenché
on:
  workflow_dispatch:
  
jobs:
  # Notre job
  build-and-deploy:
    runs-on: [macos-12]
    env:
      SNORT_PATH: ""
    # Tâches à effectuer, comme expliquées ci-dessus
    steps:
      # 1. On récupère le contenu du dépôt
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install snort"
        run: brew install snort

      - name: "Locate snort"
        run: |
          SNORT_PATH=$(which snort)
          SNORT_PATH=${SNORT_PATH%/*}
          SNORT_PATH=${SNORT_PATH%/*}
        
      - name: "Run tests"
        run: ./run_test.sh $SNORT_PATH
